Spaces to tabs

diff --git a/bin/tw_cmake b/bin/tw_cmake
--- a/bin/tw_cmake
+++ b/bin/tw_cmake
@@ -11,10 +11,10 @@
 
 if [ "$#" -ne "1" ]
 then
-    echo "Usage: $(basename "$0") [COMMAND] <teeworlds source root>"
-    echo "Commands:"
-    echo "  clean - delete all cmake build cache"
-    exit 1
+	echo "Usage: $(basename "$0") [COMMAND] <teeworlds source root>"
+	echo "Commands:"
+	echo "  clean - delete all cmake build cache"
+	exit 1
 fi
 twpath="$1"
 cmakelist="$twpath/"CMakeLists.txt
@@ -39,85 +39,87 @@ fi
 
 if [ ! -f "$cmakelist" ]
 then
-    echo "[-] Error: '$cmakelist' file not found."
-    exit 1
+	echo "[-] Error: '$cmakelist' file not found."
+	exit 1
 fi
 if [ ! -f "$datasrc_path"/game.png ] && [ -f "$twpath"/data/game.png ]
 then
-    datasrc_path="$twpath/data"
-    echo "[*] use data/ dir instead of datasrc/"
+	datasrc_path="$twpath/data"
+	echo "[*] use data/ dir instead of datasrc/"
 fi
 if [ ! -d "$datasrc_path" ]
 then
-    echo "[-] Error: '$datasrc_path' path not found."
-    exit 1
+	echo "[-] Error: '$datasrc_path' path not found."
+	exit 1
 fi
 
 function generate_data() {
-    local f
-    local files
-    if ! grep -q EXPECTED_DATA "$cmakelist"
-    then
-	    echo "[!] Warning: not EXPECTED_DATA entry found"
-	    return
-    fi
-    files=$(find "$datasrc_path" -type f \( \
-        -name "*.cfg" 	-o \
-        -name "*.frag" 	-o \
-        -name "*.json" 	-o \
-        -name "*.map" 	-o \
-        -name "*.otf" 	-o \
-        -name "*.pem" 	-o \
-        -name "*.png" 	-o \
-        -name "*.rules"	-o \
-        -name "*.txt"	-o \
-        -name "*.ttf" 	-o \
-        -name "*.ttc" 	-o \
-        -name "*.vert" 	-o \
-        -name "*.wv" \) -print0 | while IFS= read -r -d '' f
-    do
-        f="${f// /\\ }"
-        echo "  ${f/$datasrc_path\//}"
-    done | LC_ALL=C sort)
+	local f
+	local files
+	if ! grep -q EXPECTED_DATA "$cmakelist"
+	then
+		echo "[!] Warning: not EXPECTED_DATA entry found"
+		return
+	fi
+	files=$(find "$datasrc_path" -type f \( \
+		-name "*.cfg" 	-o \
+		-name "*.frag" 	-o \
+		-name "*.json" 	-o \
+		-name "*.map" 	-o \
+		-name "*.otf" 	-o \
+		-name "*.pem" 	-o \
+		-name "*.png" 	-o \
+		-name "*.rules"	-o \
+		-name "*.txt"	-o \
+		-name "*.ttf" 	-o \
+		-name "*.ttc" 	-o \
+		-name "*.vert" 	-o \
+		-name "*.wv" \) -print0 | while IFS= read -r -d '' f
+	do
+		f="${f// /\\ }"
+		echo "  ${f/$datasrc_path\//}"
+	done | LC_ALL=C sort)
 
-    pad="########################################################################"
-    empty=$(sed '/set(EXPECTED_DATA/,/)/d' "$cmakelist" | \
-        tr '\n' '\f' | \
-        sed -e "s/# DATA\\f$pad/# DATA\\f$pad\\fXXX START\\fXXX END/" | \
-        tr '\f' '\n')
-    {
-        echo "$empty" | sed -n -e '/XXX START/,$!p'
-        echo ""
-        echo "set(EXPECTED_DATA"
-        echo "$files"
-        printf ")"
-        echo "$empty" | sed -n -e '1,/XXX END/!p'
-    } > "$cmakelist"
+	pad="########################################################################"
+	empty=$(sed '/set(EXPECTED_DATA/,/)/d' "$cmakelist" | \
+		tr '\n' '\f' | \
+		sed -e "s/# DATA\\f$pad/# DATA\\f$pad\\fXXX START\\fXXX END/" | \
+		tr '\f' '\n')
+	{
+		echo "$empty" | sed -n -e '/XXX START/,$!p'
+		echo ""
+		echo "set(EXPECTED_DATA"
+		echo "$files"
+		printf ")"
+		echo "$empty" | sed -n -e '1,/XXX END/!p'
+	} > "$cmakelist"
 }
+
 function get_files_recurse() {
-    local dir="$1"
-    local oneline="$2"
-    local indent="${3:-  }"
-    local pipe=cat
-    dir="$twpath/$dir"
-    if [ "$oneline" == "1" ]
-    then
-        pipe="tr '\n' ' '"
-    fi
-    find -L "$dir" -type f \( \
-        -name "*.cpp" -o \
-        -name "*.c" -o \
-        -name "*.h" \) -print0 | while IFS= read -r -d '' f
-    do
-        f="${f// /\\ }"
-        if [ "$oneline" == "1" ]
-        then
-            printf "\n%s" "${f/$dir\//}"
-        else
-            printf "%s%s\n" "$indent" "${f/$dir\//}"
-        fi
-    done | LC_ALL=C sort | eval "$pipe"
+	local dir="$1"
+	local oneline="$2"
+	local indent="${3:-  }"
+	local pipe=cat
+	dir="$twpath/$dir"
+	if [ "$oneline" == "1" ]
+	then
+		pipe="tr '\n' ' '"
+	fi
+	find -L "$dir" -type f \( \
+		-name "*.cpp" -o \
+		-name "*.c" -o \
+		-name "*.h" \) -print0 | while IFS= read -r -d '' f
+	do
+		f="${f// /\\ }"
+		if [ "$oneline" == "1" ]
+		then
+			printf "\n%s" "${f/$dir\//}"
+		else
+			printf "%s%s\n" "$indent" "${f/$dir\//}"
+		fi
+	done | LC_ALL=C sort | eval "$pipe"
 }
+
 function get_files() {
 	local dir="$1"
 	local oneline="$2"
@@ -144,25 +146,27 @@ function get_files() {
 		fi
 	done | LC_ALL=C sort | eval "$pipe"
 }
+
 function generate_src_oneline() {
-    local set_str="$1"
-    local dir="$2"
-    local files
-    local set_str_start
-    files="$(get_files_recurse "$dir" 1)"
-    files="${files::-1}"
-    set_str_start="$(echo "$set_src" | cut -d' ' -f1-3)"
-    while IFS= read -r line
-    do
-        if [ "$line" == "$set_src" ]
-        then
-            printf "%s%s)\n" "$set_str_start" "$files"
-        else
-            echo "$line"
-        fi
-    done < "$cmakelist" > "$cmakelist.tmp"
-    mv "$cmakelist.tmp" "$cmakelist"
+	local set_str="$1"
+	local dir="$2"
+	local files
+	local set_str_start
+	files="$(get_files_recurse "$dir" 1)"
+	files="${files::-1}"
+	set_str_start="$(echo "$set_src" | cut -d' ' -f1-3)"
+	while IFS= read -r line
+	do
+		if [ "$line" == "$set_src" ]
+		then
+			printf "%s%s)\n" "$set_str_start" "$files"
+		else
+			echo "$line"
+		fi
+	done < "$cmakelist" > "$cmakelist.tmp"
+	mv "$cmakelist.tmp" "$cmakelist"
 }
+
 function generate_src() {
 	local set_str="$1"
 	local dir="$2"
@@ -201,6 +205,7 @@ function generate_src() {
 	done < "$cmakelist" > "$cmakelist.tmp"
 	mv "$cmakelist.tmp" "$cmakelist"
 }
+
 function generate_sources() {
 	local set_src
 	local recurse
@@ -242,6 +247,7 @@ function generate_sources() {
 		fi
 	done < <(grep -E '^[[:space:]]*set_(src|glob)\(' "$cmakelist")
 }
+
 generate_sources
 generate_data
 
