tw_split_logs: allow timestamps without hour and minutes

diff --git a/bin/tw_split_logs b/bin/tw_split_logs
--- a/bin/tw_split_logs
+++ b/bin/tw_split_logs
@@ -99,8 +99,20 @@ function split_log() {
 	)"
 	if [ "$ts_and_ext" == "" ]
 	then
-		echo "Error: could not parse timestamp of file '$logfile'"
-		exit 1
+		ts_and_ext="$(
+			echo "$logfile" | \
+			grep -oE '[0-9]{4}-[0-9]{2}-[0-9]{2}(.txt|.log)+$'
+		)"
+		if [ "$ts_and_ext" == "" ]
+		then
+			echo "Error: could not parse timestamp of file '$logfile'"
+			echo "       the logfile has to have a timestamp at the end of the filename"
+			echo ""
+			echo "       sample_srv_2023-08-28_21-06-27.txt"
+			echo "       sample_srv_2023-08-28.txt"
+			echo ""
+			exit 1
+		fi
 	fi
 	file_ext="${ts_and_ext##*.}"
 	file_ts="${ts_and_ext%%.*}"
