tw_split_logs: stricter checks

diff --git a/bin/tw_split_logs b/bin/tw_split_logs
--- a/bin/tw_split_logs
+++ b/bin/tw_split_logs
@@ -81,6 +81,18 @@ function split_log() {
 	local file_ts
 	local logfile
 	logfile="$1"
+
+	if [[ "$logfile" =~ / ]]
+	then
+		echo "Error: logfile '$logfile' can not contain slashes"
+		exit 1
+	fi
+	if [ ! -f "$logfile" ]
+	then
+		echo "Error: logfile not found '$logfile'"
+		exit 1
+	fi
+
 	ts_and_ext="$(
 		echo "$logfile" | \
 		grep -oE '[0-9]{4}-[0-9]{2}-[0-9]{2}_[0-9]{2}-[0-9]{2}-[0-9]{2}(.txt|.log)+$'
